---
swagger: "2.0"
info:
  description: "Activities API"
  version: "2.0.0"
  title: "Activities Service"
  termsOfService: "https://www.staffshift.com/#terms-and-conditions"
  contact:
    name: "Staffshift team"
    url: "http://www.staffshift.com"
    email: "info@staffshift.com"
host: "localhost:3100"
basePath: "/v3"
tags:
  - name: "Status"
    description: "Status of this web service"
  - name: "Activity"
    description: "Activity services"
  - name: "Advanced Search"
    description: "Activity advanced search service"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /status:
    get:
      tags:
        - Status
      summary: "Gets the status of the messaging service"
      x-swagger-router-controller: Status
      operationId: getSystemStatus
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          $ref: "#/responses/status_response"
        default:
          $ref: "#/responses/default_server_error"
  /activity:
    parameters:
      - $ref: "#/parameters/timezone_header"
    post:
      tags:
        - Activity
      summary: "Creates a new activity"
      x-swagger-router-controller: Activity
      operationId: createActivity
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/activity"
        - $ref: "#/parameters/x_request_id"
      responses:
        201:
          $ref: "#/responses/activity"
        400:
          $ref: "#/responses/activity_validation_error"
        default:
          $ref: "#/responses/default_server_error"
    get:
      tags:
        - Activity
      summary: "Retrieves a list of activities"
      x-swagger-router-controller: Activity
      operationId: getActivities
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/subject_entity_id"
        - $ref: "#/parameters/subject_entity_type"
        - $ref: "#/parameters/subject_name"
        - $ref: "#/parameters/executing_entity_id"
        - $ref: "#/parameters/executing_entity_type"
        - $ref: "#/parameters/executing_entity_name"
        - $ref: "#/parameters/executing_entity_context_id"
        - $ref: "#/parameters/executing_entity_context_type"
        - $ref: "#/parameters/created_by_entity_id"
        - $ref: "#/parameters/created_by_entity_type"
        - $ref: "#/parameters/created_by_entity_name"
        - $ref: "#/parameters/created_by_entity_context_id"
        - $ref: "#/parameters/created_by_entity_context_type"
        - $ref: "#/parameters/activity_sort_by_query"
        - $ref: "#/parameters/activity_type_filter"
        - $ref: "#/parameters/activity_id_filter"
        - $ref: "#/parameters/page"
        - $ref: "#/parameters/items_per_page"
        - $ref: "#/parameters/x_request_id"
      responses:
        200:
          $ref: "#/responses/activities"
        204:
          $ref: "#/responses/no_content"
        default:
          $ref: "#/responses/default_server_error"
  /activity/{id}:
    parameters:
      - $ref: "#/parameters/activity_id"
      - $ref: "#/parameters/x_request_id"
      - $ref: "#/parameters/timezone_header"
    get:
      tags:
        - Activity
      summary: "Retrieves the activity for the provided id"
      x-swagger-router-controller: Activity
      operationId: getActivity
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          $ref: "#/responses/activity"
        400:
          $ref: "#/responses/pattern_validation_error"
        404:
          $ref: "#/responses/resource_not_found"
        default:
          $ref: "#/responses/default_server_error"
  /activities/search:
    parameters:
      - $ref: "#/parameters/timezone_header"
      - $ref: "#/parameters/x_request_id"
    post:
      tags:
        - Advanced Search
      summary: "Advanced search on Activity records"
      x-swagger-router-controller: ActivityAdvancedSearch
      operationId: advancedSearch
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: searchCriteria
          in: body
          description: "Search criteria"
          required: false
          schema:
            $ref: "#/definitions/activity_search_query"
      responses:
        200:
          $ref: "#/responses/activities"
        204:
          $ref: "#/responses/no_content"
        400:
          description: "Validation Error. Usually caused by a missing or invalid parameter."
          schema:
            $ref: "#/definitions/activity_advanced_search_error"
        default:
          $ref: "#/responses/default_server_error"
parameters:
  x_request_id:
    name: X-Request-Id
    in: header
    description: "The request ID for the incoming payload"
    type: string
  activity_id:
    name: id
    in: path
    description: "The id of the activity"
    required: true
    type: string
    pattern: ^[0-9a-fA-F]{24}$
  activity:
    name: activity
    in: body
    description: "The activity details"
    required: true
    schema:
      $ref: "#/definitions/activity_without_id"
  activity_sort_by_query:
    name: sortBy
    description: "A comma seperated list of fields indicating sort order `name`, a negative sign reverses direction `-name`"
    required: false
    in: query
    type: array
    items:
      type: string
      enum:
      - _id
      - activity_type
      - activity_date
      - subject_entity_id
      - subject_entity_type
      - subject_name
      - executing_entity_id
      - executing_entity_type
      - executing_entity_context_id
      - executing_entity_context_type
      - executing_entity_name
      - created_by_entity_id
      - created_by_entity_type
      - created_by_entity_name
      - created_by_entity_context_id
      - created_by_entity_context_type
      - -_id
      - -activity_type
      - -activity_date
      - -subject_entity_id
      - -subject_entity_type
      - -subject_name
      - -executing_entity_id
      - -executing_entity_type
      - -executing_entity_context_id
      - -executing_entity_context_type
      - -executing_entity_name
      - -created_by_entity_id
      - -created_by_entity_type
      - -created_by_entity_name
      - -created_by_entity_context_id
      - -created_by_entity_context_type
  activity_type_filter:
    name: activity_type
    description: "Filter the type of activities that is returned"
    in: query
    type: string
    required: false
  activity_id_filter:
    name: _id
    description: "The array of activity ids to filter on"
    in: query
    type: array
    items:
      type: string
      pattern: ^[0-9a-fA-F]{24}$
    required: false
  page:
    name: page
    in: query
    description: "The page of documents to be displayed"
    required: false
    type: integer
    default: 1
    minimum: 1
  items_per_page:
    name: items_per_page
    in: query
    description: "The number of documents per page"
    required: false
    type: integer
    default: 25
    minimum: 1
  subject_entity_id:
    name: subject_entity_id
    in: query
    description: "Filter on the ID of the subject entity"
    type: string
    required: false
  subject_entity_type:
    name: subject_entity_type
    in: query
    description: "Filter on the type of the subject entity"
    type: string
    required: false
  subject_name:
    name: subject_name
    in: query
    description: "Filter on the name of the subject entity"
    type: string
    required: false
  executing_entity_id:
    name: executing_entity_id
    in: query
    description: "Filter on the ID of the subject entity"
    type: string
    required: false
  executing_entity_type:
    name: executing_entity_type
    in: query
    description: "Filter on the type of the executing entity"
    type: string
    required: false
  executing_entity_name:
    name: executing_entity_name
    in: query
    description: "Filter on the name of the executing entity"
    type: string
    required: false
  executing_entity_context_id:
    name: executing_entity_context_id
    in: query
    description: "Filter on the ID of the executing entity context"
    type: string
    required: false
  executing_entity_context_type:
    name: executing_entity_context_type
    in: query
    description: "Filter on the type of the executing entity context"
    type: string
    required: false
  created_by_entity_id:
    name: created_by_entity_id
    in: query
    description: "Filter on the ID of the created by entity"
    type: string
    required: false
  created_by_entity_type:
    name: created_by_entity_type
    in: query
    description: "Filter on the type of the created by entity"
    type: string
    required: false
  created_by_entity_name:
    name: created_by_entity_name
    in: query
    description: "Filter on the name of the created by entity"
    type: string
    required: false
  created_by_entity_context_id:
    name: created_by_entity_context_id
    in: query
    description: "Filter on the ID of the created by entity context"
    type: string
    required: false
  created_by_entity_context_type:
    name: created_by_entity_context_type
    in: query
    description: "Filter on the type of the created by entity context"
    type: string
    required: false
  timezone_header:
    name: "X-Accept-Timezone"
    required: false
    description: "The timezone dates should be converted to"
    in: header
    type: string
definitions:
  mongo_date_fields:
    type: object
    required:
      - created_at
      - updated_at
    properties:
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  activities:
    type: array
    items:
      $ref: "#/definitions/activity"
  activity:
    allOf:
      - $ref: "#/definitions/mongo_id"
      - $ref: "#/definitions/activity_without_id"
      - $ref: "#/definitions/mongo_date_fields"
  activity_without_id:
    type: object
    required:
      - activity_type
      - activity_date
    properties:
      activity_type:
        type: string
      description:
        type: string
      comment:
        type: string
      linked_entities:
        type: array
        items:
          $ref: "#/definitions/entity_object"
      activity_date:
        type: string
        format: date-time
      subject:
        $ref: "#/definitions/entity_object"
      executing_entity:
        $ref: "#/definitions/entity_with_context_object"
      created_by_entity:
        $ref: "#/definitions/entity_with_context_object"
    additionalProperties: false
  entity_object:
    type: object
    description: "Represents a dynamic link to an entity that exists in other services"
    additionalProperties: false
    required:
      - entity_type
    properties:
      entity_id:
        type: string
        description: "The id of the entity, note this doesn't have pattern matching as user don't have mongo object ids as ids"
      entity_type:
        type: string
        description: "The type of the entity this object represents"
      name:
        type: string
        description: "The name of the entity"
  entity_with_context_object:
    type: object
    description: "Represents a dynamic link to an entity that exists in other services"
    additionalProperties: false
    required:
      - entity_type
    properties:
      entity_id:
        type: string
        description: "The id of the entity, note this doesn't have pattern matching as user don't have mongo object ids as ids"
      entity_type:
        type: string
        description: "The type of the entity this object represents"
      name:
        type: string
        description: "The name of the entity"
      context_id:
        type: string
        description: "The id of the context, note this doesn't have pattern matching as user don't have mongo object ids as ids"
      context_type:
        type: string
        minLength: 1
        description: "The type of the context this object represents"
  mongo_id:
    type: object
    required:
      - _id
    properties:
      _id:
        type: string
  server_status_response:
    type: object
    required:
      - up_time
    properties:
      up_time:
        type: integer
  server_error_model:
    type: object
    required:
      - message
    properties:
      message:
        type: string
      exception:
        $ref: "#/definitions/exception_model"
  exception_model:
    type: object
  client_error_model:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  activity_validation_error_model:
    allOf:
      - $ref: "#/definitions/validation_error_model"
      - type: object
        properties:
          errors:
            type: array
            items:
              $ref: "#/definitions/activity_validation_error_single_model"
  activity_advanced_search_error:
    allOf:
      - $ref: "#/definitions/validation_error_model"
      - type: object
        properties:
          errors:
            type: array
            items:
              $ref: "#/definitions/activity_advanced_search_validation_error_single_model"
  validation_error_model:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
  activity_validation_error_single_model:
    allOf:
      - $ref: "#/definitions/validation_error_single_model"
      - type: object
        properties:
          code:
            type: string
            enum:
              - "INVALID_ACTIVITY_DATE"
              - "INVALID_TYPE"
              - "ENUM_MISMATCH"
              - "OBJECT_ADDITIONAL_PROPERTIES"
              - "MISSING_PROPERTY"
  activity_advanced_search_validation_error_single_model:
    allOf:
      - $ref: "#/definitions/validation_error_single_model"
      - type: object
        properties:
          code:
            type: string
            enum:
              - "MINIMUM"
              - "MAXIMUM"
              - "ARRAY_LENGTH_SHORT"
              - "INVALID_TYPE"
              - "ENUM_MISMATCH"
              - "OBJECT_ADDITIONAL_PROPERTIES"
  validation_error_single_model:
    type: object
    required:
      - message
      - path
    properties:
      message:
        type: string
      path:
        type: array
        items:
          type: string
      description:
        type: string
  pattern_validation_error_model:
    allOf:
      - $ref: "#/definitions/validation_error_model"
      - type: object
        properties:
          errors:
            type: array
            items:
              $ref: "#/definitions/pattern_validation_error_single_model"
  pattern_validation_error_single_model:
    allOf:
      - $ref: "#/definitions/validation_error_single_model"
      - type: object
        properties:
          code:
            type: string
            enum:
              - "PATTERN"
  activity_search_query:
    type: object
    properties:
      sort:
        type: array
        items:
          type: string
          enum:
            - "_id"
            - "-_id"
            - "activity_type"
            - "-activity_type"
            - "subject.name"
            - "-subject.name"
            - "executing_entity.name"
            - "-executing_entity.name"
            - "created_by_entity.name"
            - "-created_by_entity.name"
            - "activity_date"
            - "-activity_date"
            - "created_by_entity.entity_id"
            - "-created_by_entity.entity_id"
      page:
        type: integer
        minimum: 1
      items_per_page:
        type: integer
        minimum: 1
      query:
        type: object
        properties:
          and:
            type: array
            minItems: 1
            items:
              $ref: "#/definitions/activity_search_query_fields"
          or:
            type: array
            minItems: 1
            items:
              $ref: "#/definitions/activity_search_query_fields"
        additionalProperties: false
  activity_search_query_fields:
    type: object
    properties:
      activity_type:
        $ref: "#/definitions/advanced_search_operations_string_field"
      linked_entities:
        type: object
        properties:
          contains:
            type: array
            items:
              $ref: "#/definitions/activity_search_query_entity_fields"
          contains_any:
            type: array
            items:
              $ref: "#/definitions/activity_search_query_entity_fields"
        additionalProperties: false
      subject:
        $ref: "#/definitions/activity_search_query_entity_fields"
      activity_date:
        $ref: "#/definitions/advanced_search_operations_date_field"
      executing_entity:
        $ref: "#/definitions/activity_search_query_entity_with_context_fields"
      created_by_entity:
        $ref: "#/definitions/activity_search_query_entity_with_context_fields"
    additionalProperties: false
  activity_search_query_entity_fields:
    type: object
    properties:
      entity_id:
        $ref: "#/definitions/advanced_search_operations_string_field"
      entity_type:
        $ref: "#/definitions/advanced_search_operations_string_field"
      name:
        $ref: "#/definitions/advanced_search_operations_string_field"
    additionalProperties: false
  activity_search_query_entity_with_context_fields:
    type: object
    properties:
      entity_id:
        $ref: "#/definitions/advanced_search_operations_string_field"
      entity_type:
        $ref: "#/definitions/advanced_search_operations_string_field"
      name:
        $ref: "#/definitions/advanced_search_operations_string_field"
      context_id:
        $ref: "#/definitions/advanced_search_operations_string_field"
      context_type:
        $ref: "#/definitions/advanced_search_operations_string_field"
    additionalProperties: false
responses:
  activity:
    description: "The retrieved activity"
    schema:
      $ref: "#/definitions/activity"
  activities:
    description: "List of retrieved activities"
    headers:
      x-result-count:
        type: number
      link:
        type: string
    schema:
      $ref: "#/definitions/activities"
  no_content:
    headers:
      link:
        type: string
      x-result-count:
        type: integer
    description: "No entities found that match the query"
  resource_not_found:
    description: "No resource found for ID"
    schema:
      $ref: "#/definitions/client_error_model"
  activity_validation_error:
    description: "A validation error occurred"
    schema:
      $ref: "#/definitions/activity_validation_error_model"
  pattern_validation_error:
    description: "A validation error occurred"
    schema:
      $ref: "#/definitions/pattern_validation_error_model"
  status_response:
    description: "The server status will be returned"
    schema:
      $ref: "#/definitions/server_status_response"
  default_server_error:
    description: "unexpected error"
    schema:
      $ref: "#/definitions/server_error_model"